import { writeFile, mkdir, readdir, readFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import { join } from "node:path";
import { knowledgeDirFor } from "./registry.ts";

const ARCHITECT_KEYS = ["product", "architecture", "code_map", "glossary", "stack_rules"] as const;
type ArchitectKey = (typeof ARCHITECT_KEYS)[number];

/** Ожидаемые ключи JSON-вывода архитектора → имя файла. */
const KEY_TO_FILE: Record<ArchitectKey, string> = {
  product: "00-project/product.md",
  architecture: "00-project/architecture.md",
  code_map: "00-project/code-map.md",
  glossary: "00-project/glossary.md",
  stack_rules: "00-project/stack-rules.md",
};

export interface ArchitectResult {
  product: string;
  architecture: string;
  code_map: string;
  glossary: string;
  stack_rules: string;
}

/**
 * Распарсить вывод архитектора в структуру.
 * Переваривает: голый JSON, JSON в ```json fence, лишний текст вокруг.
 * Возвращает null если JSON невалиден или нет ни одного ожидаемого ключа.
 */
export function parseArchitectJson(output: string): ArchitectResult | null {
  // 1. Попытка вытащить JSON из fence ```json ... ```
  let jsonStr: string | null = null;
  const fenceMatch = output.match(/```(?:json)?\s*\n?([\s\S]*?)```/);
  if (fenceMatch) {
    jsonStr = fenceMatch[1]!.trim();
  } else {
    // 2. Попытка найти первый { и последний } (голый JSON, возможно с текстом вокруг)
    const firstBrace = output.indexOf("{");
    const lastBrace = output.lastIndexOf("}");
    if (firstBrace !== -1 && lastBrace > firstBrace) {
      jsonStr = output.slice(firstBrace, lastBrace + 1);
    }
  }
  if (!jsonStr) return null;

  let parsed: Record<string, unknown>;
  try {
    parsed = JSON.parse(jsonStr);
  } catch {
    return null;
  }

  // Проверяем, что есть хотя бы один ожидаемый ключ.
  const result: Partial<ArchitectResult> = {};
  let found = 0;
  for (const key of ARCHITECT_KEYS) {
    const val = parsed[key];
    if (typeof val === "string" && val.trim().length > 0) {
      result[key] = val;
      found++;
    }
  }
  if (found === 0) return null;
  // Заполняем отсутствующие ключи заглушкой
  for (const key of ARCHITECT_KEYS) {
    if (!(key in result)) {
      result[key] = `<!-- ${key}: not generated by architect -->`;
    }
  }
  return result as ArchitectResult;
}

/**
 * Записать распарсенный результат архитектора в 00-project/*.md.
 */
export async function writeProjectFiles(slug: string, parsed: ArchitectResult): Promise<void> {
  const dir = knowledgeDirFor(slug);
  const projectDir = join(dir, "00-project");
  await mkdir(projectDir, { recursive: true });
  for (const key of ARCHITECT_KEYS) {
    const file = KEY_TO_FILE[key];
    const content = parsed[key];
    await writeFile(join(dir, file), content, "utf8");
  }
}

/**
 * Просканировать структуру проекта для контекста архитектора.
 * Возвращает строку с ls корня, package.json/README (если есть), tree -L 2.
 * Это единственная роль, где context = live-скан, а не директория знаний.
 */
export async function scanProjectStructure(projectPath: string): Promise<string> {
  const parts: string[] = [];

  // 1. Listing корня
  try {
    const entries = await readdir(projectPath, { withFileTypes: true });
    const listing = entries
      .filter((e) => !e.name.startsWith("."))
      .map((e) => `${e.isDirectory() ? "[D]" : "[F]"} ${e.name}`)
      .join("\n");
    parts.push(`ROOT LISTING:\n${listing}`);
  } catch {
    parts.push("ROOT LISTING: (unable to read)");
  }

  // 2. package.json (если есть)
  const pkgPath = join(projectPath, "package.json");
  if (existsSync(pkgPath)) {
    try {
      const pkg = JSON.parse(await readFile(pkgPath, "utf8"));
      parts.push(
        `PACKAGE.JSON:\n${JSON.stringify({
          name: pkg.name,
          version: pkg.version,
          type: pkg.type,
          scripts: pkg.scripts,
          dependencies: pkg.dependencies ? Object.keys(pkg.dependencies) : [],
          devDependencies: pkg.devDependencies ? Object.keys(pkg.devDependencies) : [],
        }, null, 2)}`,
      );
    } catch {
      parts.push("PACKAGE.JSON: (unparseable)");
    }
  }

  // 3. README (первые 2000 символов)
  for (const readmeName of ["README.md", "README.txt", "README"]) {
    const readmePath = join(projectPath, readmeName);
    if (existsSync(readmePath)) {
      try {
        const content = await readFile(readmePath, "utf8");
        parts.push(`README (${readmeName}):\n${content.slice(0, 2000)}`);
      } catch {
        // skip
      }
      break;
    }
  }

  // 4. Дерево поддиректорий (глубина 2, без node_modules/.git)
  try {
    const tree = await buildTree(projectPath, "", 2);
    parts.push(`DIRECTORY TREE:\n${tree}`);
  } catch {
    parts.push("DIRECTORY TREE: (unable to build)");
  }

  return parts.join("\n\n---\n\n");
}

/** Рекурсивно построить дерево директорий (до maxDepth), исключая шум. */
async function buildTree(dir: string, prefix: string, maxDepth: number): Promise<string> {
  if (maxDepth <= 0) return "";
  const SKIP = new Set(["node_modules", ".git", "dist", ".next", ".orchestrator", "__pycache__"]);
  let result = "";
  try {
    const entries = await readdir(dir, { withFileTypes: true });
    const visible = entries
      .filter((e) => !SKIP.has(e.name) && !e.name.startsWith("."))
      .sort((a, b) => {
        if (a.isDirectory() !== b.isDirectory()) return a.isDirectory() ? -1 : 1;
        return a.name.localeCompare(b.name);
      });
    for (const e of visible) {
      result += `${prefix}${e.isDirectory() ? "[" + e.name + "]" : e.name}\n`;
      if (e.isDirectory()) {
        result += await buildTree(join(dir, e.name), prefix + "  ", maxDepth - 1);
      }
    }
  } catch {
    // permission denied etc
  }
  return result;
}
